name: Compile changelogs

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  compile:
    name: "Compile changelogs"
    runs-on: ubuntu-24.04
    if: github.repository == 'Lobotomy-Corporation-13/lc13' # Do not run on forks
    steps:
      - name: "Setup python"
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: "Install deps"
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
          sudo apt-get install  dos2unix
      - name: "Checkout"
        uses: actions/checkout@v1
        with:
          fetch-depth: 25
      - name: "Compile"
        run: |
          python tools/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: "Convert Lineendings"
        run: |
          unix2dos html/changelogs/.all_changelog.yml
      - name: Commit
        run: |
          git config user.name "Cupax3Bot"
          git config user.email "85813370+Cupax3Bot@users.noreply.github.com"
          git pull origin master
          git commit -m "Automatic changelog compile [ci skip]" -a || true
      - name: "Push"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
