name: Compile changelogs

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  compile:
    name: "Compile changelogs"
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    if: github.repository == 'Lobotomy-Corporation-13/lc13' # Do not run on forks
    steps:
      - name: "Setup python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: "Install deps"
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
          sudo apt-get install  dos2unix
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 25
          persist-credentials: false
      - name: "Compile"
        run: |
          python tools/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: "Convert Lineendings"
        run: |
          unix2dos html/changelogs/.all_changelog.yml
      - name: Commit
        run: |
          git config --local user.name "lc13-automation[bot]"
          git config --local user.email "230900368+lc13-automation[bot]@users.noreply.github.com"
          git pull origin master
          git add html/changelogs
          git commit -m "Automatic changelog compile [ci skip]" -a || true
      - name: Generate App Token
        id: app-token-generation
        uses: actions/create-github-app-token@v2
        if: env.APP_PRIVATE_KEY != '' && env.APP_ID != ''
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_ID: ${{ secrets.APP_ID }}
      - name: "Push"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.app-token-generation.outputs.token || secrets.GITHUB_TOKEN }}
